const fs = require('node:fs');
const source = fs.readFileSync('src/js/core/SoundManager.js','utf8').replace(/\r\n/g, '\n').replace(/import Logger[^\n]*\n/, 'const Logger = { log(){}, warn:console.warn };\n').replace('export default class SoundManager', 'class SoundManager');
const scores = Object.fromEntries(fs.readdirSync('assets/data/music').filter(f=>f.endsWith('.json')).map(f=>[f.replace('.json',''), JSON.parse(fs.readFileSync('assets/data/music/'+f))]));
const labels={bgm_intro:'로그인 · 캐릭터 선택',bgm_cabin:'바람 언덕',bgm_act1_peaceful:'안개빛 호수',bgm_act2_threat:'뇌광 숲',bgm_act4_hope:'별그늘 유적',bgm_rift:'태초의 균열지',bgm_boss:'보스',bgm_act3_sacrifice:'서사 테마 · 예비곡',bgm_battle:'기존 전투 테마 · 예비곡'};
const html = `<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>유리카 · 사운드 청음실</title>
<style>*{box-sizing:border-box}body{margin:0;background:#10151e;color:#e5edf6;font:16px/1.65 system-ui,sans-serif}main{max-width:1060px;margin:auto;padding:42px 24px}h1{font-size:32px;letter-spacing:-1px;margin:0}p{color:#a7b8cc}header{margin-bottom:26px}.controls{background:#192333;z-index:1;padding:18px;border:1px solid #3b4d66;border-radius:14px;display:flex;gap:16px;align-items:center;flex-wrap:wrap}.controls label{display:flex;gap:8px;align-items:center;font-size:14px}input{width:110px;accent-color:#8adbc7}button{font:inherit;border:1px solid #51657f;border-radius:8px;background:#23334a;color:#eef5ff;padding:8px 15px;cursor:pointer}button:hover,button[aria-pressed=true]{background:#326254;border-color:#8adbc7}button:focus-visible{outline:3px solid #e9c875;outline-offset:3px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(265px,1fr));gap:16px;margin:24px 0}.card{background:#18212e;border:1px solid #304158;border-radius:14px;padding:22px}.card h2{font-size:19px;margin:0 0 4px}.card p{font-size:14px;min-height:46px;margin:5px 0 16px}.meta{font-size:13px;color:#9db0c8;margin-bottom:16px}.sfx{display:flex;gap:10px;flex-wrap:wrap}#status{color:#a1e7d5;min-height:28px}small{color:#9db0c8}</style>
<main><header><small>YURIKA ONLINE / SOUND STUDY</small><h1>유리카 사운드 청음실</h1><p>지역별 음악과 효과음을 비교해 보세요. 곡은 반복 재생되며, 다른 곡을 누르면 부드럽게 전환됩니다.</p></header>
<div class="controls"><button id="stop">전체 정지</button><label>전체 <input aria-label="전체 음량" id="master" type="range" min="0" max="100" value="40"><output id="masterOut">40%</output></label><label>음악 <input aria-label="음악 음량" id="bgm" type="range" min="0" max="100" value="65"><output id="bgmOut">65%</output></label><label>효과음 <input aria-label="효과음 음량" id="sfx" type="range" min="0" max="100" value="85"><output id="sfxOut">85%</output></label></div>
<p id="status" role="status" aria-live="polite">재생할 곡을 선택하세요.</p><div class="grid" id="tracks"></div><h2>효과음 샘플</h2><p>음악을 재생하면서 효과음을 누르면 함께 들을 수 있습니다.</p><div class="sfx" id="effects"></div><p><small>오프라인에서 열 수 있는 청음용 파일입니다. 게임의 JSON 악보와 합성 엔진을 포함하며 외부 오디오 파일이나 서버 연결은 사용하지 않습니다. 예비곡은 현재 필드 배경음과 구분해 표시했습니다.</small></p></main>
<script>${source}
const scores=${JSON.stringify(scores)},labels=${JSON.stringify(labels)};
let sound=new SoundManager({loadJSON:async url=>scores[url.split('/').pop().replace('.json','')]});
const status=document.querySelector('#status');
async function ready(){sound.init();await sound.resume();if(sound.ctx.state!=='running')throw Error('브라우저에서 오디오 재생을 허용해주세요.');}
async function run(action){try{await ready();action();}catch(e){status.textContent=e.message;}}
function mark(id){document.querySelectorAll('[data-track]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.track===id)));}
for(const [id,label] of Object.entries(labels)){const d=scores[id],secs=Math.max(...d.tracks.map(t=>t.notes.reduce((s,n)=>s+n[1],0)))*60/d.bpm;const card=document.createElement('article');card.className='card';const h=document.createElement('h2');h.textContent=label;const p=document.createElement('p');p.textContent=d.title;const meta=document.createElement('div');meta.className='meta';meta.textContent=d.bpm+' BPM · '+secs.toFixed(1)+'초 · '+d.tracks.length+'개 파트';const btn=document.createElement('button');btn.textContent='▶ 재생';btn.dataset.track=id;btn.setAttribute('aria-pressed','false');btn.setAttribute('aria-label',label+' 재생');btn.onclick=()=>run(()=>{sound.playBgm(d,id);mark(id);status.textContent='재생 중 · '+label;});card.append(h,p,meta,btn);document.querySelector('#tracks').append(card);}
for(const [id,label] of Object.entries({deep_shock:'기본 공격',fireball_cast:'화염 시전',fireball_explosion:'화염 폭발',missile_hit:'미사일 타격',shield_activate:'보호막',crit:'치명타',sfx_slime_attack:'슬라임 공격',sfx_slime_hit:'슬라임 피격',sfx_slime_die:'슬라임 소멸',monster_charge:'돌진 경고',boss_spawn:'보스 등장',item_pickup:'아이템 획득',ui_click:'버튼 클릭'})){const b=document.createElement('button');b.textContent=label;b.onclick=()=>run(()=>sound.playSfx(id));document.querySelector('#effects').append(b);}
for(const [id,method] of [['master','setMasterVolume'],['bgm','setBgmVolume'],['sfx','setSfxVolume']])document.getElementById(id).oninput=e=>{sound[method](Number(e.target.value)/100);document.getElementById(id+'Out').textContent=e.target.value+'%';};
document.querySelector('#stop').onclick=async()=>{sound.stopBgm();if(sound.ctx){await sound.ctx.close();sound.ctx=null;sound.isInitialized=false;}mark(null);status.textContent='재생을 정지했습니다.';};
</script></html>`;
fs.mkdirSync('reports/audio',{recursive:true});fs.writeFileSync('reports/audio/yurika-audio-preview.html',html);
console.log('reports/audio/yurika-audio-preview.html ('+Buffer.byteLength(html)+' bytes)');
