/* A local, four-person RPG UI concept. It does not modify the original game's account or combat. */
(() => {
 'use strict';
 const D=window.PARTY_DATA, chars=Object.fromEntries(D.characters.map(c=>[c.id,c])), ids=Object.keys(chars);
 const app=document.querySelector('#app'), dialog=document.querySelector('#dialog'), dialogContent=document.querySelector('#dialog-content');
 const KEY='yurika.party-rpg.concept.v1';
 const defaults=()=>({version:1,party:[...D.initialParty],gold:2500,books:16,stones:6,potions:4,levels:Object.fromEntries(D.characters.map(c=>[c.id,c.level])),equipment:Object.fromEntries(ids.map(id=>[id,0])),purchases:Object.fromEntries(D.products.map(p=>[p.id,0])),clanJoined:false,clanPoints:0,claimDay:'',donationDay:'',settings:{motion:true,haptics:false,sound:true}});
 const clamp=(n,lo,hi,fallback)=>Number.isFinite(n)?Math.min(hi,Math.max(lo,Math.floor(n))):fallback;
 function load(){
  const s=defaults();try{
   const raw=JSON.parse(localStorage.getItem(KEY));if(!raw||raw.version!==1)return s;
   for(const k of ['gold','books','stones','potions','clanPoints'])s[k]=clamp(raw[k],0,999999,s[k]);
   if(Array.isArray(raw.party)&&raw.party.length===4&&raw.party[0]===D.leaderId&&new Set(raw.party).size===4&&raw.party.every(id=>ids.includes(id)))s.party=[...raw.party];
   for(const id of ids){s.levels[id]=clamp(raw.levels?.[id],1,30,s.levels[id]);s.equipment[id]=clamp(raw.equipment?.[id],0,5,0);}
   for(const p of D.products)s.purchases[p.id]=clamp(raw.purchases?.[p.id],0,9,0);
   s.clanJoined=raw.clanJoined===true;s.claimDay=typeof raw.claimDay==='string'?raw.claimDay:'';s.donationDay=typeof raw.donationDay==='string'?raw.donationDay:'';
   for(const k of ['motion','haptics','sound'])if(typeof raw.settings?.[k]==='boolean')s.settings[k]=raw.settings[k];
  }catch(_){/* Continue with a safe starting party if local storage is unavailable/corrupt. */}return s;
 }
 let saved=load();const ui={route:'opening',started:false,character:'mage',tab:'growth',slot:1,draft:[...saved.party],region:'wind',loadError:null,pendingRoute:null,filter:'all',clanTab:'notice',gearItem:'weapon',skillItem:'active'};
 let toastTimer,speechTimer,bootFrame,bootGeneration=0,audio;
 const paths={home:'M3 11 12 3l9 8M5 10v11h5v-7h4v7h5V10',party:'M8 10a3 3 0 1 0 0-6 3 3 0 0 0 0 6Zm8 1a3 3 0 1 0 0-6 3 3 0 0 0 0 6ZM2 21v-4a6 6 0 0 1 12 0v4m1-7c4 0 7 2 7 6',wand:'m4 20 14-14m-2-2 4 4M4 4h4M6 2v4m9 12h5m-2-2v5',shield:'M12 2 3 6v6c0 5 9 10 9 10s9-5 9-10V6l-9-4Zm0 4v12',book:'M12 5C9 2 4 3 3 4v16c3-2 6-2 9 0 3-2 6-2 9 0V4c-1-1-6-2-9 1Zm0 0v15',bow:'M4 3c12 1 15 10 16 17L4 3Zm0 0v17h16M4 20 17 7m-4 0h4v4',shop:'M3 9h18l-2-6H5L3 9ZM4 10v11h16V10M9 21v-7h6v7',clan:'M7 9a5 5 0 1 0 10 0 5 5 0 0 0-10 0ZM3 22a9 9 0 0 1 18 0',coin:'M3 12a9 9 0 1 0 18 0 9 9 0 0 0-18 0Zm9-6 4 6-4 6-4-6 4-6Z',gem:'m3 9 4-6h10l4 6-9 12L3 9Zm0 0h18M7 3l5 18 5-18',potion:'M9 3h6M10 3v6l-5 8c-1 3 1 4 3 4h8c2 0 4-1 3-4l-5-8V3M8 14h8',arrow:'M4 12h16m-6-6 6 6-6 6',back:'M20 12H4m6-6-6 6 6 6',check:'m4 12 5 5 11-11',gear:'M9 3h6l1 3 3 1 2 5-2 3-3 1-1 5H9l-1-5-3-1-2-3 2-5 3-1 1-3Zm-1 9a4 4 0 1 0 8 0 4 4 0 0 0-8 0',heart:'M12 21C-3 11 1 2 8 4l4 4 4-4c7-2 11 7-4 17Z',compass:'M3 12a9 9 0 1 0 18 0 9 9 0 0 0-18 0Zm13-4-2 6-6 2 2-6 6-2Z',close:'m5 5 14 14M19 5 5 19',crown:'M3 6 7 9l5-6 5 6 4-3-2 14H5L3 6Z'};
 const icon=(n,size=20)=>`<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[n]||paths.book}"/></svg>`;
 const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const amount=n=>n.toLocaleString('ko-KR');
 const today=()=>new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Seoul'});
 const thumb=id=>`<span class="thumb"><img src="assets/${chars[id].idle}" alt=""></span>`;
 const bg=(file,environment='lobby')=>`<div class="backdrop" data-environment="${environment}"><img src="assets/${file}" alt="" fetchpriority="high"></div>`;
 function stats(id){const c=chars[id],level=saved.levels[id],gear=saved.equipment[id];return{hp:c.hp+level*25,atk:c.atk+level*7+gear*12,def:c.def+level*4+gear*8};}
 const power=party=>party.filter(Boolean).reduce((sum,id)=>{const s=stats(id);return sum+Math.round(s.hp*.25+s.atk*2+s.def*1.5);},0);
 const complete=party=>party.length===4&&party[0]===D.leaderId&&new Set(party).size===4&&party.every(id=>ids.includes(id));
 const dirty=()=>JSON.stringify(ui.draft)!==JSON.stringify(saved.party);
 function save(){try{localStorage.setItem(KEY,JSON.stringify(saved));}catch(_){toast('이 브라우저에서는 이번 방문 동안만 기록이 유지됩니다.');}}
 function toast(message){clearTimeout(toastTimer);const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');toastTimer=setTimeout(()=>el.classList.remove('show'),2700);}
 function feedback(){if(!saved.settings.sound)return;try{const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;audio||=new AC();if(audio.state==='suspended')audio.resume().catch(()=>{});const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.setValueAtTime(650,audio.currentTime);o.frequency.exponentialRampToValueAtTime(410,audio.currentTime+.065);g.gain.setValueAtTime(.035,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.08);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+.08);}catch(_){}}
 function modal(title,body,actions){dialogContent.innerHTML=`<h2 id="dialog-title">${esc(title)}</h2>${body}<div class="dialog-actions">${actions}</div>`;if(!dialog.open)dialog.showModal();}
 const close=()=>dialog.close();
 const button=(label,action,kind='primary',attrs='')=>`<button class="button ${kind}" data-action="${action}" ${attrs}>${label}</button>`;
 function topbar(title,extra=''){const companion=['party','characters'].includes(ui.route);return`<header class="topbar"><div class="top-left">${ui.route==='lobby'?`<button class="brand" data-go="lobby" aria-label="대기실">YURIKA<small>달숲 야영지</small></button>`:`<button class="icon-button" data-go="lobby" aria-label="대기실로 돌아가기">${icon('back')}</button><strong class="page-title">${companion?'동료':title}</strong>`}${companion?`<nav class="section-switch" aria-label="동료 메뉴"><button data-go="party" class="${ui.route==='party'?'active':''}">파티 편성</button><button data-go="characters" class="${ui.route==='characters'?'active':''}">캐릭터 관리</button></nav>`:''}</div><div class="top-right">${extra}<span class="resource">${icon('coin',17)}<strong id="gold-count">${amount(saved.gold)}</strong><small>골드</small></span><span class="resource">${icon('book',17)}<strong>${saved.books}</strong><small>경험의 서</small></span><button class="icon-button" data-action="settings" aria-label="설정">${icon('gear',19)}</button></div></header>`; }
 function nav(){const active=['party','characters'].includes(ui.route)?'party':ui.route;const items=[['lobby','home','대기실'],['party','party','동료'],['shop','shop','상점'],['clan','clan','클랜']];return`<nav class="bottom-nav" aria-label="주 메뉴">${items.map(([id,i,n])=>`<button class="nav-item ${id===active?'active':''}" data-go="${id}" ${id===active?'aria-current="page"':''}>${icon(i)}<span>${n}</span></button>`).join('')}</nav>`;}
 function opening(){return`<div class="opening-visual" style="--art-url:url('assets/opening.png')"><img src="assets/opening.png" alt="함께 모험을 떠나는 네 동료"></div><div class="opening-copy"><p class="eyebrow">MOONFOREST</p><h1>YURIKA</h1><p class="subtitle">ONLINE</p><h2>네 사람이 함께 여는 모험</h2></div><div class="boot-footer"><div class="loading-block"><div class="row loading-status"><span id="load-text">달숲으로 가는 길을 준비하고 있어요.</span><span id="load-percent">0%</span></div><div class="loading-line" role="progressbar" aria-label="시작 준비" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="loading-fill"></div></div></div><div class="start-area"><button class="button gold start-button" data-action="start" hidden>START ${icon('arrow')}</button><button class="button ghost" data-action="retry-load" hidden>이미지 다시 불러오기</button><p id="start-hint">잠시 후 이야기가 시작됩니다.</p></div></div>`;}
 function lobby(){const claimed=saved.claimDay===today();return`${bg('camp-background.png')}${topbar('',`<button class="daily-gift" data-action="daily" ${claimed?'disabled':''} aria-label="${claimed?'준비 선물 수령 완료':'여행 준비 선물 받기'}">${icon(claimed?'check':'book',16)}<span>${claimed?'수령 완료':'준비 선물'}</span></button>`)}<div class="camp-viewport"><main class="camp-stage" aria-label="현재 편성된 동료들의 야영지"><img class="camp-prop" src="assets/camp-table.png" alt="지도와 차가 놓인 야영 테이블">${saved.party.map(id=>`<button class="camp-actor camp-${id}" data-talk="${id}" aria-label="${chars[id].short} · ${chars[id].campActivity}"><img class="camp-art" src="assets/${chars[id].camp}" alt="${chars[id].campActivity} 중인 ${chars[id].short}"></button>`).join('')}</main></div><footer class="lobby-dock"><aside class="camp-party"><button class="party-shortcut" data-go="party" aria-label="현재 4인 파티 편성">${icon('party',20)}<span><strong>4 / 4 편성</strong><small>전투력 ${amount(power(saved.party))}</small></span></button></aside><aside class="departure-card"><button class="button gold full" data-go="expedition"><span><strong>원정 출발</strong><small>바람 언덕</small></span>${icon('arrow',18)}</button></aside></footer>${nav()}`;}

 function party(){const chosen=ui.draft[ui.slot],valid=complete(ui.draft),pool=D.characters.filter(c=>ui.filter==='all'||c.group===ui.filter),delta=power(ui.draft)-power(saved.party);return`${bg('camp-background.png')}${topbar()}<main class="content party-layout"><section class="party-editor"><div class="section-title"><h1>함께 떠날 네 사람</h1><p>자리를 선택한 뒤 동료를 고르세요.</p></div><div class="slot-grid" aria-label="4인 파티 자리">${ui.draft.map((id,i)=>`<button class="slot ${i===ui.slot?'active':''} ${id?'':'empty'}" data-slot="${i}" aria-pressed="${i===ui.slot}" aria-label="${i===0?'고정 주인공':`동료 ${i}`} ${id?chars[id].short:'빈 자리'}"><span class="slot-number">${i===0?'주인공 · 고정':'동료 '+i}</span>${id?`<img src="assets/${chars[id].idle}" alt=""><div class="slot-caption"><strong>${chars[id].short}</strong><small>Lv.${saved.levels[id]} · ${chars[id].job}</small><span>${chars[id].skill}</span></div>`:'<span class="slot-empty-icon">＋</span><strong>동료 선택</strong>'}</button>`).join('')}</div><footer class="party-actions"><span class="formation-status ${valid?'':'incomplete'}">${ui.draft.filter(Boolean).length} / 4 편성 <strong>${amount(power(ui.draft))}</strong>${delta?`<small class="${delta<0?'negative':'positive'}">${delta>0?'+':''}${delta}</small>`:''}</span><div class="action-group">${button('되돌리기','cancel-party','ghost')}${button('편성 저장','save-party','gold',valid?'':'disabled')}</div></footer></section><aside class="paper picker"><header class="row"><h2>보유 동료</h2><small>${D.characters.length}명</small></header><div class="filters" aria-label="동료 역할 필터">${[['all','전체'],['attack','공격'],['support','지원']].map(([id,n])=>`<button class="${ui.filter===id?'active':''}" data-filter="${id}" aria-pressed="${ui.filter===id}">${n}</button>`).join('')}</div><div class="pool-grid">${pool.map(c=>`<button class="pool-card ${ui.draft.includes(c.id)?'in-party':''}" data-pick="${c.id}" ${c.id===D.leaderId?'disabled':''} aria-label="${c.short} 편성">${thumb(c.id)}<span><strong>${c.short}</strong><small>${c.id===D.leaderId?'주인공 고정':c.job}</small><em>${ui.draft.includes(c.id)?'편성 중':'선택 가능'}</em></span></button>`).join('')}</div><div class="selected-info"><small>선택한 자리 · ${ui.slot===0?'주인공':'동료 '+ui.slot}</small><strong>${chosen?chars[chosen].short:'비어 있는 자리'}</strong><p>${chosen?chars[chosen].skill+' · '+chars[chosen].job:'목록에서 동료를 선택하세요.'}</p></div><footer class="picker-actions">${button('자리 비우기','remove-member','soft',ui.slot===0||!chosen?'disabled':'')}${button('관리','manage-selected','primary',!chosen?'disabled':'')}</footer></aside></main>${nav()}`;}
 function characterBody(c){const level=saved.levels[c.id],gear=saved.equipment[c.id],s=stats(c.id);if(ui.tab==='growth')return`<div class="management-scroll"><div class="stats"><span class="stat">생명력<strong>${amount(s.hp)}</strong><small>${level<30?'+25':''}</small></span><span class="stat">공격력<strong>${s.atk}</strong><small>${level<30?'+7':''}</small></span><span class="stat">방어력<strong>${s.def}</strong><small>${level<30?'+4':''}</small></span></div><p class="character-story">${c.story}</p></div><footer class="management-action"><p class="growth-cost">${level>=30?'성장 단계 완료':`Lv.${level} → ${level+1} · 경험의 서 2 + 골드 100`}</p>${button(level>=30?'최대 레벨':'레벨 올리기','level-up','primary full',level>=30||saved.books<2||saved.gold<100?'disabled':'')}</footer>`;if(ui.tab==='equipment'){const items=[['weapon',c.weapon,c.icon,`공격력 +${gear*12} · 방어력 +${gear*8}`],['armor',c.armor,'shield','동료의 역할에 어울리는 기본 장비'],['accessory',c.accessory,'gem','함께한 여정의 작은 기억']];return`<div class="management-scroll equipment-list">${items.map(([id,n,i,detail])=>`<button class="equipment-item ${ui.gearItem===id?'active':''}" data-gear-item="${id}" aria-expanded="${ui.gearItem===id}"><span class="item-icon">${icon(i,19)}</span><span><strong>${n}${id==='weapon'?' +'+gear:''}</strong>${ui.gearItem===id?`<small>${detail}</small>`:''}</span>${icon(ui.gearItem===id?'check':'arrow',13)}</button>`).join('')}</div><footer class="management-action"><p class="growth-cost">${gear>=5?'정비 단계 완료':`무기 +${gear} → +${gear+1} · 정비석 1 + 골드 ${150+gear*50}`}</p>${button(gear>=5?'강화 완료':'무기 강화','gear-up','primary full',gear>=5||saved.stones<1||saved.gold<150+gear*50?'disabled':'')}</footer>`;}return`<div class="management-scroll skill-list">${[['active',c.skill,c.icon,c.skillText],['support',c.support,'heart',c.supportText]].map(([id,n,i,detail])=>`<button class="equipment-item ${ui.skillItem===id?'active':''}" data-skill-item="${id}" aria-expanded="${ui.skillItem===id}"><span class="item-icon">${icon(i,19)}</span><span><strong>${n}</strong><small>${id==='active'?'기본 기술':'파티 역할'}</small>${ui.skillItem===id?`<p>${detail}</p>`:''}</span></button>`).join('')}</div>`;}
 function characters(){const c=chars[ui.character];return`<div class="key-visual" style="--focus:${c.focus||'35%'};--art-url:url('assets/${c.key}')"><img src="assets/${c.key}" alt="${c.name}의 컨펌 원화"></div>${topbar()}<main class="content character-layout"><nav class="character-rail" aria-label="관리할 캐릭터">${D.characters.map(c=>`<button class="rail-button ${c.id===ui.character?'active':''}" data-character="${c.id}" aria-pressed="${c.id===ui.character}">${thumb(c.id)}<span>${c.short}</span></button>`).join('')}</nav><section class="paper character-panel"><header><div class="row"><h2>${c.short}</h2><span class="badge">Lv.${saved.levels[c.id]}</span></div><small>${c.name} · ${c.job}</small></header><div class="tabs" role="tablist" aria-label="캐릭터 관리 항목">${[['growth','성장'],['equipment','장비'],['skills','스킬']].map(([id,n])=>`<button class="tab ${ui.tab===id?'active':''}" data-tab="${id}" role="tab" aria-selected="${ui.tab===id}">${n}</button>`).join('')}</div><div class="character-body" role="tabpanel">${characterBody(c)}</div></section></main>${nav()}`;}

 function scene(file,label,focus='0%'){return`<figure class="scene-window" style="--scene-focus:${focus};--art-url:url('assets/${file}')" aria-label="${label}"><img src="assets/${file}" alt="${label}"></figure>`;}
 function shop(){return`${topbar('상점')}<main class="content shop-layout">${scene('shop.png','잡화점에서 물건을 살펴보는 위치와 마법사')}<section class="shop-display" aria-label="여행 준비 물품"><header class="shop-heading"><div><h2>달숲 잡화점</h2><p>다음 모험을 위한 작은 준비.</p></div></header><div class="product-grid">${D.products.map(p=>{const stock=9-(saved.purchases[p.id]||0);return`<article class="product"><img class="product-art" src="assets/${p.art}" alt="${p.name}"><div class="product-copy"><small>${p.quantity}개 묶음</small><h3>${p.name}</h3><p>${p.use}</p><span class="stock">남은 수량 ${stock}</span></div><button class="button primary" data-product="${p.id}" ${stock===0||saved.gold<p.price?'disabled':''}>${stock===0?'품절':`${icon('coin',14)} ${amount(p.price)}`}</button></article>`;}).join('')}</div><footer class="inventory-strip"><span>보유품</span><span>${icon('book',13)} ${saved.books}</span><span>${icon('gem',13)} ${saved.stones}</span><span>${icon('potion',13)} ${saved.potions}</span></footer></section></main>${nav()}`;}

 function clan(){const joined=saved.clanJoined;let body='';if(ui.clanTab==='notice')body=`<div class="notice"><small>오늘의 공지</small><h3>바람 언덕, 함께 준비해요.</h3><p>출발 전에 동료의 장비와 파티를 확인해주세요.<br>각자의 속도로, 함께 멀리 가기.</p><span>달빛 나무지기 · 콘셉트 공지</span></div><div class="clan-meeting"><span>${icon('compass',19)}</span><div><strong>다음 여정 · 바람 언덕</strong><small>4인 파티로 준비하는 첫 번째 모험</small></div><button class="text-button" data-go="expedition">원정 보기 ${icon('arrow',14)}</button></div>`;else if(ui.clanTab==='members')body=`<div class="members-scroll">${[[joined?'여행자 · 나':'새 여행자를 기다리는 자리','mage',joined?'기여 '+saved.clanPoints:'가입 후 함께해요'],['달빛 나무지기','witch','클랜장'],['숲길 안내자','guardian','부클랜장'],['바람의 여행자','archer','클랜원']].map(([name,id,role])=>`<div class="member">${thumb(id)}<strong>${name}</strong><small>${role}</small></div>`).join('')}</div><p class="fine">멤버 목록은 화면 흐름을 위한 예시입니다.</p>`;else body=`<div class="clan-goal"><span class="tag">이번 여정의 공동 목표</span><h3>야영지의 작은 준비</h3><p>여행 골드를 모아 동료들의 다음 여정을 응원해요.</p><div class="row"><strong>${saved.clanPoints} / 500</strong><small>나의 기여 ${saved.clanPoints}</small></div><div class="goal-track"><span style="width:${Math.min(100,saved.clanPoints/5)}%"></span></div></div>`;return`${topbar('클랜')}<main class="content clan-layout">${scene('clan.png','클랜의 다음 여정을 함께 준비하는 네 동료')}<section class="paper clan-dashboard"><header class="clan-header"><div><h2>달빛 나무</h2><small>Lv.3 · ${joined?'13':'12'} / 30명${joined?' · 함께 머무는 중':''}</small></div>${joined?button('클랜 떠나기','leave-clan','soft small'):button('함께 머물기','join-clan','primary small')}</header><nav class="tabs" aria-label="클랜 게시판">${[['notice','공지'],['members','멤버'],['goal','공동 목표']].map(([id,n])=>`<button class="tab ${ui.clanTab===id?'active':''}" data-clan-tab="${id}" aria-pressed="${ui.clanTab===id}">${n}</button>`).join('')}</nav><div class="clan-tab-body">${body}</div>${ui.clanTab==='goal'?`<footer class="clan-goal-action">${button(saved.donationDay===today()?'오늘의 기여 완료':'기여하기 · 100 골드','donate','primary full',!joined||saved.donationDay===today()||saved.gold<100?'disabled':'')}</footer>`:''}</section></main>${nav()}`;}

 function expedition(){const r=D.regions.find(r=>r.id===ui.region);return`${topbar('원정 준비')}<main class="content expedition-layout">${scene(r.file,r.name+'의 풍경','28%')}<section class="paper briefing"><nav class="region-tabs" aria-label="원정 지역">${D.regions.map(r=>`<button class="${r.id===ui.region?'active':''}" data-region="${r.id}" aria-pressed="${r.id===ui.region}">${r.name}</button>`).join('')}</nav><div class="briefing-scroll"><header><small>다음 여정</small><h2>${r.name}</h2><p>${r.subtitle}</p></header><div class="mini-party">${saved.party.map(id=>`<div class="mini-member">${thumb(id)}<span>${chars[id].short} Lv.${saved.levels[id]}</span></div>`).join('')}</div><div class="row"><small>파티 전투력 ${amount(power(saved.party))}</small><small>권장 ${amount(r.power)}</small></div></div><footer>${button('이 파티로 출발 준비','depart','primary full')}</footer></section></main>${nav()}`;}

 const renderers={opening,lobby,party,characters,shop,clan,expedition};
 function render(){clearTimeout(speechTimer);app.className=`app screen-${ui.route}`;app.dataset.environment=ui.route;app.innerHTML=renderers[ui.route]();window.YurikaMotion?.refresh();}
 function navigate(route){if(!ui.started)return;if(!renderers[route]||route==='opening')return;close();if(route==='party'&&ui.route!=='party'){ui.draft=[...saved.party];ui.slot=1;}ui.route=route;history.replaceState(null,'',`#${route}`);render();}
 function requestNavigation(route){if(route===ui.route)return;if(ui.route==='party'&&dirty()){ui.pendingRoute=route;modal('편성 변경을 남겨둘까요?','<p>변경한 파티는 아직 대기실에 반영되지 않았습니다.</p>',`${button('계속 편성','close','soft')}${button('변경 취소하고 이동','discard-go','soft')}${button('저장하고 이동','save-go','primary',complete(ui.draft)?'':'disabled')}`);return;}navigate(route);}
 function commitParty(){if(!complete(ui.draft)){toast('주인공과 서로 다른 동료 3명을 채워주세요.');return false;}saved.party=[...ui.draft];save();toast('네 사람의 자리를 저장했어요.');return true;}
 function pick(id){if(ui.slot===0||id==='mage'){toast('주인공의 자리는 고정되어 있어요.');return;}const old=ui.draft[ui.slot],existing=ui.draft.indexOf(id);if(existing===ui.slot){toast('이미 이 자리에 편성되어 있어요.');return;}if(existing>0)ui.draft[existing]=old;ui.draft[ui.slot]=id;render();toast(existing>0?'두 동료의 자리를 바꿨어요.':'동료를 편성했어요.');}
 function settings(){modal('우리의 대기실',`<div class="setting-row"><span><strong>일러스트 움직임</strong><small>동료의 가벼운 호흡과 배경 움직임</small></span><button class="toggle ${saved.settings.motion?'on':''}" data-setting="motion" aria-pressed="${saved.settings.motion}">${saved.settings.motion?'켜짐':'꺼짐'}</button></div><div class="setting-row"><span><strong>버튼 진동</strong><small>지원하는 기기에서만 반응합니다</small></span><button class="toggle ${saved.settings.haptics?'on':''}" data-setting="haptics" aria-pressed="${saved.settings.haptics}">${saved.settings.haptics?'켜짐':'꺼짐'}</button></div><div class="setting-row"><span><strong>버튼 효과음</strong><small>선택할 때 작은 소리가 납니다</small></span><button class="toggle ${saved.settings.sound?'on':''}" data-setting="sound" aria-pressed="${saved.settings.sound}">${saved.settings.sound?'켜짐':'꺼짐'}</button></div><p class="dialog-note">4인 수집형 RPG 화면 콘셉트입니다. 편성·성장·구매·클랜 체험은 이 브라우저에 저장됩니다.</p>`,`${button('전체 화면','fullscreen','soft')}${button('닫기','close')}`);}
 function action(a,b){switch(a){
  case 'start':if(!ui.bootReady)return;ui.started=true;navigate('lobby');break;
  case 'retry-load':boot();break;
  case 'close':close();break;
  case 'close-speech':clearTimeout(speechTimer);app.querySelector('.speech')?.remove();app.querySelectorAll('.camp-actor').forEach(a=>a.classList.remove('talking'));break;
  case 'settings':settings();break;
  case 'fullscreen':if(document.fullscreenElement){document.exitFullscreen?.();}else if(document.documentElement.requestFullscreen){document.documentElement.requestFullscreen().catch(()=>toast('이 브라우저에서는 전체 화면 전환이 제한됩니다.'));}else toast('기기의 브라우저 전체 화면 기능을 사용해주세요.');break;
  case 'save-party':if(commitParty())render();break;
  case 'cancel-party':ui.draft=[...saved.party];render();toast('저장된 파티로 되돌렸어요.');break;
  case 'remove-member':if(ui.slot===0)return;ui.draft[ui.slot]=null;render();break;
  case 'manage-selected':if(!ui.draft[ui.slot])return;ui.character=ui.draft[ui.slot];ui.tab='growth';requestNavigation('characters');break;
  case 'discard-go':ui.draft=[...saved.party];navigate(ui.pendingRoute||'lobby');ui.pendingRoute=null;break;
  case 'save-go':if(commitParty()){navigate(ui.pendingRoute||'lobby');ui.pendingRoute=null;}break;
  case 'daily':if(saved.claimDay===today())return;saved.claimDay=today();saved.gold+=200;saved.books+=2;save();render();toast('골드 200과 경험의 서 2권을 준비했어요.');break;
  case 'level-up':{const id=ui.character;if(saved.levels[id]>=30||saved.books<2||saved.gold<100)return;saved.books-=2;saved.gold-=100;saved.levels[id]++;save();render();toast(`${chars[id].short} Lv.${saved.levels[id]} · 생명력 +25 / 공격력 +7 / 방어력 +4`);break;}
  case 'gear-up':{const id=ui.character,cost=150+saved.equipment[id]*50;if(saved.equipment[id]>=5||saved.stones<1||saved.gold<cost)return;saved.stones--;saved.gold-=cost;saved.equipment[id]++;save();render();toast(`${chars[id].weapon} +${saved.equipment[id]} · 공격력 +12 / 방어력 +8`);break;}
  case 'buy':{const p=D.products.find(p=>p.id===b.dataset.id);if(!p)return;if((saved.purchases[p.id]||0)>=9||saved.gold<p.price){close();toast('골드나 남은 꾸러미를 확인해주세요.');return;}saved.gold-=p.price;saved[p.resource]+=p.quantity;saved.purchases[p.id]=(saved.purchases[p.id]||0)+1;save();close();render();toast(`${p.name}을 준비했어요.`);break;}
  case 'join-clan':if(saved.clanJoined)return;saved.clanJoined=true;save();render();toast('달빛 나무에 함께 머물게 되었어요.');break;
  case 'donate':if(!saved.clanJoined||saved.donationDay===today()||saved.gold<100)return;saved.gold-=100;saved.clanPoints+=100;saved.donationDay=today();save();render();toast('클랜에 작은 마음 100을 보탰어요.');break;
  case 'leave-clan':modal('달빛 나무를 떠날까요?','<p>여행자의 파티와 성장 기록은 그대로 이어집니다.</p>',`${button('머무르기','close','soft')}${button('떠나기','confirm-leave')}`);break;
  case 'confirm-leave':saved.clanJoined=false;save();close();render();toast('언제든 다시 찾아올 수 있어요.');break;
  case 'depart':{const r=D.regions.find(r=>r.id===ui.region);modal('네 사람의 준비가 끝났어요.',`<p>${r.name}으로 향하는 파티입니다.</p><div class="mini-party">${saved.party.map(id=>`<div class="mini-member">${thumb(id)}<span>${chars[id].short}</span></div>`).join('')}</div><p class="fine">이 콘셉트의 출전 흐름은 여기까지입니다. 4인 전투는 Unity 제작 단계에서 연결합니다.</p>`,`${button('파티 다시 살펴보기','depart-party','soft')}${button('대기실로','depart-lobby')}`);break;}
  case 'depart-party':close();navigate('party');break;
  case 'depart-lobby':close();navigate('lobby');break;
 }}
 document.addEventListener('click',event=>{
  const b=event.target.closest('button');if(!b||b.disabled)return;feedback();
  if(b.dataset.go){requestNavigation(b.dataset.go);return;}
  if(b.dataset.inspect){ui.character=b.dataset.inspect;ui.tab='growth';requestNavigation('characters');return;}
  if(b.dataset.filter){ui.filter=b.dataset.filter;render();return;}
  if(b.dataset.clanTab){ui.clanTab=b.dataset.clanTab;render();return;}
  if(b.dataset.gearItem){ui.gearItem=b.dataset.gearItem;render();return;}
  if(b.dataset.skillItem){ui.skillItem=b.dataset.skillItem;render();return;}
  if(b.dataset.slot!==undefined){ui.slot=Number(b.dataset.slot);render();return;}
  if(b.dataset.pick){pick(b.dataset.pick);return;}
  if(b.dataset.character){ui.character=b.dataset.character;render();return;}
  if(b.dataset.tab){ui.tab=b.dataset.tab;render();return;}
  if(b.dataset.region){ui.region=b.dataset.region;render();return;}
  if(b.dataset.talk){const id=b.dataset.talk;app.querySelector('.speech')?.remove();app.querySelectorAll('.camp-actor').forEach(a=>a.classList.toggle('talking',a===b));const bubble=document.createElement('aside');bubble.className='speech';bubble.setAttribute('role','status');bubble.innerHTML=`<strong>${chars[id].short}<small>${chars[id].campActivity}</small></strong><p>${chars[id].quote}</p><button class="text-button" data-inspect="${id}">캐릭터 관리 ${icon('arrow',13)}</button><button class="speech-close" data-action="close-speech" aria-label="대사 닫기">${icon('close',16)}</button>`;app.append(bubble);clearTimeout(speechTimer);speechTimer=setTimeout(()=>{bubble.remove();b.classList.remove('talking');},5500);return;}

  if(b.dataset.product){const p=D.products.find(p=>p.id===b.dataset.product);modal(p.name,`<p>${p.description}</p><div class="rule"></div><p>사용 골드 <strong>${p.price}</strong><br>구매 후 골드 <strong>${amount(saved.gold-p.price)}</strong></p>`,`${button('다음에','close','soft')}${button('구매하기','buy','primary',`data-id="${p.id}"`)}`);return;}
  if(b.dataset.setting){const k=b.dataset.setting;saved.settings[k]=!saved.settings[k];save();window.YurikaMotion?.init({enabled:saved.settings.motion,haptics:saved.settings.haptics,feedback:true});settings();return;}
  if(b.dataset.action)action(b.dataset.action,b);
 });
 function loadImage(file){return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve();img.onerror=()=>reject(new Error(file));img.src=`assets/${file}`;});}
 function boot(){
  const generation=++bootGeneration;cancelAnimationFrame(bootFrame);ui.route='opening';ui.bootReady=false;ui.loadError=null;render();
  const startedAt=performance.now();let assetsReady=false,failed=[];
  Promise.allSettled(['opening.png','camp-background.png','camp-table.png',...D.characters.flatMap(c=>[c.idle,c.key,c.camp])].map(loadImage)).then(results=>{if(generation!==bootGeneration)return;failed=results.filter(r=>r.status==='rejected').map(r=>r.reason.message);assetsReady=true;});
  function update(now){if(generation!==bootGeneration)return;const elapsed=now-startedAt;const percent=Math.min(assetsReady&&!failed.length?100:95,Math.floor(elapsed/10));const fill=app.querySelector('.loading-fill');if(!fill)return;fill.style.width=percent+'%';app.querySelector('#load-percent').textContent=percent+'%';app.querySelector('[role="progressbar"]').setAttribute('aria-valuenow',percent);
   if(elapsed>=1000&&assetsReady){if(failed.length){ui.loadError=failed;app.querySelector('#load-text').textContent='일부 그림을 불러오지 못했어요.';app.querySelector('[data-action="retry-load"]').hidden=false;app.querySelector('#start-hint').textContent='다시 불러오기를 눌러주세요.';}else{ui.bootReady=true;app.querySelector('#load-text').textContent='모험 준비가 끝났어요.';app.querySelector('[data-action="start"]').hidden=false;app.querySelector('#start-hint').textContent='클릭하거나 터치해서 시작하세요.';}return;}bootFrame=requestAnimationFrame(update);
  }bootFrame=requestAnimationFrame(update);
 }
 dialog.addEventListener('click',event=>{if(event.target===dialog){const r=dialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)close();}});
 window.addEventListener('hashchange',()=>{if(!ui.started)return;const target=location.hash.slice(1);if(renderers[target]&&target!=='opening')requestNavigation(target);});
 const portrait=window.matchMedia('(orientation: portrait)');let dismissedPortrait=false;function rotate(){document.querySelector('#rotate').hidden=!portrait.matches||dismissedPortrait;}
 document.querySelector('#dismiss-rotate').addEventListener('click',()=>{dismissedPortrait=true;rotate();});portrait.addEventListener?.('change',rotate);rotate();
 window.YurikaMotion?.init({enabled:saved.settings.motion,haptics:saved.settings.haptics,feedback:true});
 window.PartyConcept=Object.freeze({snapshot:()=>JSON.parse(JSON.stringify({saved,ui:{route:ui.route,bootReady:ui.bootReady,character:ui.character,slot:ui.slot,draft:ui.draft}}))});
 boot();
})();
